name = input("whats your name?")
print (f"hello {name}")
print (f"how was your day {name}")
name2 = input("")
print (f"my day was also {name2}")
print ("how about a story")
input ("")
print ("who's your best friend?")
animal = input ("")
print ("now your favorite place")
place = input ("")
print (f"there ones was a {animal} in {place}")
print("roaming around and he stumbled upon")
print ("what did he find?")
thing = input ("")
print ("what did he do with it?")
action = input ("")
print ("how did he feel?")
feeling = input("")
print ("heres the story!")
input ("")
print (f"ones {name2} was wandering around {place} and stumbled upon {thing} they did {action} and they felt {feeling}")
input ("")
print ("the end!!!!!!!!")